# permissions for end users to view lvmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmcluster-viewer-role
rules:
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmclusters/status
  verbs:
  - get
